import { DigitalReceipt } from '@/components/digital-receipt'

export default function ReceiptsPage() {
  return (
    <div className="flex flex-col items-center justify-center p-4">
      <div className="w-full max-w-md mx-auto">
        <h1 className="text-2xl font-bold text-center mb-2 font-headline">
          Trust-Stamped Digital Receipt
        </h1>
        <p className="text-center text-muted-foreground mb-6">
          This is a sample of the tamper-evident digital receipts generated by
          DiraBiz.
        </p>
        <DigitalReceipt />
      </div>
    </div>
  )
}
